# coding: utf-8

"""
    HPC Web API

    Preview  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import hpc_acm
from hpc_acm.models.node_metrics import NodeMetrics  # noqa: E501
from hpc_acm.rest import ApiException


class TestNodeMetrics(unittest.TestCase):
    """NodeMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeMetrics(self):
        """Test NodeMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hpc_acm.models.node_metrics.NodeMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
