# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
  allow_failures:
    - python: "3.7"
# command to install dependencies
install: "pip install flake8 -r requirements.txt"
# stop the build if there are Python syntax errors or undefined names
before_script: flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
# command to run tests
script: nosetests
