# coding: utf-8

"""
    HPC Web API

    Preview  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NodeSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ok': 'float',
        'warning': 'float',
        'error': 'float'
    }

    attribute_map = {
        'ok': 'OK',
        'warning': 'Warning',
        'error': 'Error'
    }

    def __init__(self, ok=None, warning=None, error=None):  # noqa: E501
        """NodeSummary - a model defined in Swagger"""  # noqa: E501

        self._ok = None
        self._warning = None
        self._error = None
        self.discriminator = None

        if ok is not None:
            self.ok = ok
        if warning is not None:
            self.warning = warning
        if error is not None:
            self.error = error

    @property
    def ok(self):
        """Gets the ok of this NodeSummary.  # noqa: E501

        number of nodes that are OK  # noqa: E501

        :return: The ok of this NodeSummary.  # noqa: E501
        :rtype: float
        """
        return self._ok

    @ok.setter
    def ok(self, ok):
        """Sets the ok of this NodeSummary.

        number of nodes that are OK  # noqa: E501

        :param ok: The ok of this NodeSummary.  # noqa: E501
        :type: float
        """

        self._ok = ok

    @property
    def warning(self):
        """Gets the warning of this NodeSummary.  # noqa: E501

        number of nodes that has warning  # noqa: E501

        :return: The warning of this NodeSummary.  # noqa: E501
        :rtype: float
        """
        return self._warning

    @warning.setter
    def warning(self, warning):
        """Sets the warning of this NodeSummary.

        number of nodes that has warning  # noqa: E501

        :param warning: The warning of this NodeSummary.  # noqa: E501
        :type: float
        """

        self._warning = warning

    @property
    def error(self):
        """Gets the error of this NodeSummary.  # noqa: E501

        number of nodes that has error  # noqa: E501

        :return: The error of this NodeSummary.  # noqa: E501
        :rtype: float
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this NodeSummary.

        number of nodes that has error  # noqa: E501

        :param error: The error of this NodeSummary.  # noqa: E501
        :type: float
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
