# coding: utf-8

"""
    HPC Web API

    Preview  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from hpc_acm.models.node_metrics_items import NodeMetricsItems  # noqa: F401,E501


class NodeMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'span': 'float',
        'items': 'list[NodeMetricsItems]'
    }

    attribute_map = {
        'span': 'span',
        'items': 'items'
    }

    def __init__(self, span=None, items=None):  # noqa: E501
        """NodeMetrics - a model defined in Swagger"""  # noqa: E501

        self._span = None
        self._items = None
        self.discriminator = None

        if span is not None:
            self.span = span
        if items is not None:
            self.items = items

    @property
    def span(self):
        """Gets the span of this NodeMetrics.  # noqa: E501

        Time span in second of the metric data  # noqa: E501

        :return: The span of this NodeMetrics.  # noqa: E501
        :rtype: float
        """
        return self._span

    @span.setter
    def span(self, span):
        """Sets the span of this NodeMetrics.

        Time span in second of the metric data  # noqa: E501

        :param span: The span of this NodeMetrics.  # noqa: E501
        :type: float
        """

        self._span = span

    @property
    def items(self):
        """Gets the items of this NodeMetrics.  # noqa: E501


        :return: The items of this NodeMetrics.  # noqa: E501
        :rtype: list[NodeMetricsItems]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this NodeMetrics.


        :param items: The items of this NodeMetrics.  # noqa: E501
        :type: list[NodeMetricsItems]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
