# coding: utf-8

"""
    HPC Web API

    Preview  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NodeMetricsMetricItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'instance_values': 'dict(str, float)'
    }

    attribute_map = {
        'category': 'category',
        'instance_values': 'instanceValues'
    }

    def __init__(self, category=None, instance_values=None):  # noqa: E501
        """NodeMetricsMetricItems - a model defined in Swagger"""  # noqa: E501

        self._category = None
        self._instance_values = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if instance_values is not None:
            self.instance_values = instance_values

    @property
    def category(self):
        """Gets the category of this NodeMetricsMetricItems.  # noqa: E501

        Metric category  # noqa: E501

        :return: The category of this NodeMetricsMetricItems.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this NodeMetricsMetricItems.

        Metric category  # noqa: E501

        :param category: The category of this NodeMetricsMetricItems.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def instance_values(self):
        """Gets the instance_values of this NodeMetricsMetricItems.  # noqa: E501

        Metric data  # noqa: E501

        :return: The instance_values of this NodeMetricsMetricItems.  # noqa: E501
        :rtype: dict(str, float)
        """
        return self._instance_values

    @instance_values.setter
    def instance_values(self, instance_values):
        """Sets the instance_values of this NodeMetricsMetricItems.

        Metric data  # noqa: E501

        :param instance_values: The instance_values of this NodeMetricsMetricItems.  # noqa: E501
        :type: dict(str, float)
        """

        self._instance_values = instance_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeMetricsMetricItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
